spring.application.name=backend
springdoc.swagger-ui.path=/docs

spring.datasource.url=jdbc:postgresql://localhost:5432/courseexamples
spring.datasource.username=swen2user
spring.datasource.password=swen2pw
spring.jpa.hibernate.ddl-auto=create
