services:
  db:
    image: postgres:18
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: swen2user
      POSTGRES_PASSWORD: swen2pw
      POSTGRES_DB: courseexamples

volumes:
  pg_data:
